name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - uses: actions/checkout@v4  
      - name: Docker Build
        run: docker compose build
      - name: Run docker compose 
        run: docker compose up -d
      - name: Check running containers
        run: docker ps -a  
      - name: Test with pytest
        run: docker exec pytest-action-test-api-1 pytest
      # - name: Stop and remove containers
      #   run: docker compose down